language: node_js
node_js:
  - "lts/*"

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  file_glob: true
  file: ./dist/index.html
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: gh-pages
  on:
    branch: master
